const PRODUCTS_LOAD_REQUEST = '@products/LOAD_REQUEST';
const PRODUCTS_LOAD_SUCCESS = '@products/LOAD_SUCCESS';
const PRODUCTS_LOAD_FAILURE = '@products/LOAD_FAILURE';

export { PRODUCTS_LOAD_REQUEST, PRODUCTS_LOAD_SUCCESS, PRODUCTS_LOAD_FAILURE };
