const CART_ADD_PRODUCT = '@cart/ADD_PRODUCT';
const CART_REMOVE_PRODUCT = '@cart/REMOVE_PRODUCT';
const CART_INCREASE_QUANTITY = '@cart/INCREASE_QUANTITY';
const CART_DECREASE_QUANTITY = '@cart/DECREASE_QUANTITY';

export { CART_ADD_PRODUCT, CART_REMOVE_PRODUCT, CART_INCREASE_QUANTITY, CART_DECREASE_QUANTITY };
